[
{
	"id":"1",
	"namaKost":"Kost Persona Alam",
	"alamatKost": "Jl. Rungkut Asri 3",
	"nomorTelepon":"08944135832",
	"jumlahKamar":10,
	"kamarTerpakai":5,
	"fasilitasKost":["Wifi","Kamar Mandi Dalam","Laundry", "Garasi", "Dapur Umum"],
	"harga":500000,
	"tagLineKost":"Kost Murah Meriah",
	"jenisKost":"Putra",
	"rating":4.0,
	"urlPhoto":"https://storage.googleapis.com/finansialku_media/wordpress_media/2018/02/Ketahui-Manajemen-Rumah-Kost-Dengan-Baik-dan-Benar-01-Finansialku.jpg"
},{
	"id":"2",
	"namaKost":"Kost Putra Ubaya",
	"alamatKost": "Jl. Rungkut Penjaringan IV/80",
	"nomorTelepon":"08941416721",
	"jumlahKamar":20,
	"kamarTerpakai":7,
	"fasilitasKost":["Kantin","Kamar Mandi Luar","TV", "Wifi"],
	"harga":750000,
	"tagLineKost":"Kost Dekat Ubaya",
	"jenisKost":"Putra",
	"rating":3.6,
	"urlPhoto":"https://berita.99.co/wp-content/uploads/2022/08/kost-gaya-kekinian.jpg"
},{
	"id":"3",
	"namaKost":"Kost AM Ubaya",
	"alamatKost": "Jl. Tenggilis Medokan no 50",
	"nomorTelepon":"089771161425",
	"jumlahKamar":14,
	"kamarTerpakai":12,
	"fasilitasKost":["Wifi","Kamar Mandi Luar","View Ubaya", "Lapangan Futsal", "Dapur Umum"],
	"harga":1500000,
	"tagLineKost":"Kost Go Green",
	"jenisKost":"Putra/Putri",
	"rating":3.0,
	"urlPhoto":"https://storage.googleapis.com/finansialku_media/wordpress_media/2017/10/Tips-Membangun-Rumah-Kost-Yang-Menguntungkan-01-Finansialku.jpg"
},{
	"id":"4",
	"namaKost":"Kost Putri Ubaya",
	"alamatKost": "Jl. Rungkut Menanggal 91",
	"nomorTelepon":"086974513612",
	"jumlahKamar":10,
	"kamarTerpakai":7,
	"fasilitasKost":["Dapur", "Mesin Cuci","Lahan Parkir", "Ruang Makan"],
	"harga":950000,
	"tagLineKost":"Kost Dekat Ubaya",
	"jenisKost":"Putri",
	"rating":3.7,
	"urlPhoto":"https://binabangunbangsa.com/wp-content/uploads/2020/03/tips-Manajemen-Rumah-Kost-yang-Baik-dan-Benar-.jpg"
},{
	"id":"5",
	"namaKost":"Kost AN 51",
	"alamatKost": "Jl. Tenggilis Mejoyo 50A",
	"nomorTelepon":"08795185231",
	"jumlahKamar":5,
	"kamarTerpakai":2,
	"fasilitasKost":["Kamar Mandi Bath Up", "WiFi","Telepon Umum"],
	"harga":1050000,
	"tagLineKost":"Kost Masa Depan",
	"jenisKost":"Putri",
	"rating":4.0,
	"urlPhoto":"https://lh3.googleusercontent.com/hDy2Iu-H9xEnR0yjdoXGDSUGsPRggMb-N5NJe5c1fOlXx4wAODpn4ORFI1MxBJBT-sbRfHV9cKewlUnAkCBPbW8apzsJxxxRwLSP6JfeEhypWXM3w7SkMo6r8cdf8XGpe3lfjI4I"
},{
	"id":"6",
	"namaKost":"Kost Pangeran Ubaya",
	"alamatKost": "Jl. Rungkut Jayakarta No.16",
	"nomorTelepon":"08123456789",
	"jumlahKamar":20,
	"kamarTerpakai":10,
	"fasilitasKost":["AC","Kamar Mandi Dalam","Parkir Motor", "Dapur Umum"],
	"harga":1200000,
	"tagLineKost":"Nyaman dan Strategis",
	"jenisKost":"Putra/Putri",
	"rating":4.0,
	"urlPhoto":"https://www.pajak.com/storage/2022/03/rumah-kos.jpg"
},{
	"id":"7",
	"namaKost":"Kost Fajar Ubaya",
	"alamatKost": "Jl. Rungkut Indah II No.12",
	"nomorTelepon":"08123456785",
	"jumlahKamar":12,
	"kamarTerpakai":9,
	"fasilitasKost":["AC","Kamar Mandi Dalam","Parkir Motor", "Dapur Umum"],
	"harga":1500000,
	"tagLineKost":"Lingkungan Asri",
	"jenisKost":"Putri",
	"rating":3.0,
	"urlPhoto":"https://lh4.googleusercontent.com/hEnSBHI0LPx0Y-uAv1x5V8FiZZEMAnPoaghnn3EjehuW4nc8d2Jne7wj2hnzvU6IVZrx2y7OUQlHTaArjazMgS58hNWSEaZFx270E05JgB-S3aov727WDdgsTPiMJYOkSZqsgtdpGYowcodo7pGgkWluyGpzbKPUdhqzbzwn74DZRXlpvpPymplx70Sh4GVSGA4wCHc0Dg"
},{
	"id":"8",
	"namaKost":"Kost Jaya Baru",
	"alamatKost": "Jl. Rungkut Industri No.5",
	"nomorTelepon":"08123456786",
	"jumlahKamar":10,
	"kamarTerpakai":8,
	"fasilitasKost":["Kamar Mandi Luar","Parkir Motor", "Dapur Umum"],
	"harga":1800000,
	"tagLineKost":"Harga Kost Terjangkau",
	"jenisKost":"Putra/Putri",
	"rating":3.5,
	"urlPhoto":"https://infobekasi.co/wp-content/uploads/2017/11/kost.jpg"
},{
	"id":"9",
	"namaKost":"Kost Kenanga",
	"alamatKost": "Jl. Tenggilis Mejoyo II No.11",
	"nomorTelepon":"08941412274",
	"jumlahKamar":8,
	"kamarTerpakai":5,
	"fasilitasKost":["AC","Kamar Mandi Luar","Parkir Motor", "WiFi"],
	"harga":1500000,
	"tagLineKost":"Hemat dan Bersih",
	"jenisKost":"Putra",
	"rating":3.5,
	"urlPhoto":"https://pix10.agoda.net/hotelImages/135/1353767/1353767_16081917290045634234.jpg?ca=6&ce=1&s=1024x768"
},{
	"id":"10",
	"namaKost":"Kost Melati",
	"alamatKost": "Jl. Tenggilis IV No.11",
	"nomorTelepon":"08123456788",
	"jumlahKamar":15,
	"kamarTerpakai":10,
	"fasilitasKost":["AC","Kamar Mandi Dalam","Parkir Motor", "Dapur Umum"],
	"harga":1800000,
	"tagLineKost":"Nyaman dan Tenang",
	"jenisKost":"Putri",
	"rating":4.0,
	"urlPhoto":"https://pindahlubang.com/wp-content/uploads/2021/04/Biaya-Bangun-Rumah-Kost-2-Lantai.jpg"
}
]